name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: LP Wikis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: lua-changed-files
        uses: tj-actions/changed-files@v32
        with:
          files: |
            components/**/*.lua
            standard/**/*.lua

      - id: res-changed-files
        uses: tj-actions/changed-files@v32
        with:
          files: |
            stylesheets/**/*.css
            stylesheets/**/*.less
            stylesheets/**/*.scss
            javascript/**/*.js

      - name: Resource Deploy
        if: steps.res-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_USER }}
          WIKI_PASSWORD: ${{ secrets.LP_PASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
        run: bash scripts/deploy_res.sh "${{ steps.res-changed-files.outputs.all_changed_files }}"

      - name: Lua Deploy
        if: steps.lua-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_USER }}
          WIKI_PASSWORD: ${{ secrets.LP_PASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
        run: bash scripts/deploy.sh "${{ steps.lua-changed-files.outputs.all_changed_files }}"

  dev-deploy:
    name: Dev Wikis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - id: changed-files
        uses: tj-actions/changed-files@v32
        with:
          files: |
            components/**/*.lua
            standard/**/*.lua

      - name: Deploy Old Dev
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.DEV_WIKI_USER }}
          WIKI_PASSWORD: ${{ secrets.DEV_WIKI_PASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.DEV_WIKI_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.DEV_WIKI_BASE_URL }}
          DEV_WIKI_BASIC_AUTH: ${{ secrets.DEV_WIKI_BASIC_AUTH }}
        run: bash scripts/deploy.sh "${{ steps.changed-files.outputs.all_changed_files }}"

      - name: Deploy New Dev
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.DEV_WIKI_USER }}
          WIKI_PASSWORD: ${{ secrets.DEV_WIKI_PASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.DEV_WIKI_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.DEV_WIKI_BASE_URL2 }}
          DEV_WIKI_BASIC_AUTH: ${{ secrets.DEV_WIKI_BASIC_AUTH }}
        run: bash scripts/deploy.sh "${{ steps.changed-files.outputs.all_changed_files }}"
