name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: LP Wikis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: lua-changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            lua/wikis/**/*.lua

      - id: res-changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            stylesheets/**/*.css
            stylesheets/**/*.less
            stylesheets/**/*.scss
            javascript/**/*.js

      - name: Resource Deploy
        if: steps.res-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          DEPLOY_TRIGGER: ${{ github.event_name }}
        run: bash scripts/deploy_res.sh "${{ steps.res-changed-files.outputs.all_changed_files }}"

      - name: Lua Deploy
        if: steps.lua-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          DEPLOY_TRIGGER: ${{ github.event_name }}
        run: bash scripts/deploy.sh "${{ steps.lua-changed-files.outputs.all_changed_files }}"

      - name: Lua Protect
        # sadly .any_added nor .any_renamed do not exist ...
        if: steps.lua-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
        run: bash scripts/protect.sh "${{ steps.lua-changed-files.outputs.added_files }} ${{ steps.lua-changed-files.outputs.renamed_files }}"
