name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: LP Wikis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - id: lua-changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            lua/wikis/**/*.lua

      - id: res-changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            stylesheets/**/*.scss
            javascript/**/*.js

      - name: Setup Python
        if: steps.res-changed-files.outputs.any_changed == 'true' || steps.lua-changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'


      - name: Install Python Dependency
        if: steps.res-changed-files.outputs.any_changed == 'true' || steps.lua-changed-files.outputs.any_changed == 'true'
        run: pip install requests

      - name: Resource Deploy
        if: steps.res-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          DEPLOY_TRIGGER: ${{ github.event_name }}
        run: python3 ./scripts/deploy_res.py ${{ steps.res-changed-files.outputs.all_changed_files }}

      - name: Lua Deploy
        if: steps.lua-changed-files.outputs.any_changed == 'true'
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          DEPLOY_TRIGGER: ${{ github.event_name }}
        run: python3 ./scripts/deploy.py ${{ steps.lua-changed-files.outputs.all_changed_files }}

      - name: Lua Protect
        if: steps.lua-changed-files.outputs.added_files_count != 0 || steps.lua-changed-files.outputs.renamed_files_count != 0
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
        run: python3 ./scripts/protect.py ${{ steps.lua-changed-files.outputs.added_files }} ${{ steps.lua-changed-files.outputs.renamed_files }}
