name: Lua Code Style and Unit Tests

on: [pull_request, workflow_dispatch]

jobs:
  lua-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: '5.1'

      - name: Setup luarock
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install --lua-version=5.1 luacheck

      - name: Run lint
        run: |
          luacheck ./ |
          luacheck ./ --formatter=JUnit > report.xml

      - name: Report lint
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'report.xml'
          check_name: 'Lint Report'

  lua-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: '5.1'

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup dependencies
        run: |
          luarocks install --lua-version=5.1 busted

      - name: Run test
        run: |
          busted -v --run=ci --output=junit > busted.xml

      - name: Report test
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'busted.xml'
          check_name: 'Test Report'
