name: Lua Code Style and Unit Tests

on: [pull_request, workflow_dispatch]

jobs:
  lua-code-style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup lua
        uses: Liquipedia/gh-actions-lua@316cadd2e8345ee977caa64ac0d192e15d932f73
        with:
          luaVersion: '5.1'

      - name: Setup luarock
        uses: leafo/gh-actions-luarocks@v5

      - name: Setup dependencies
        run: |
          luarocks install --lua-version=5.1 luacheck

      - name: Run lint
        run: |
          luacheck lua --config lua/.luacheckrc |
          luacheck lua --config lua/.luacheckrc --formatter=JUnit > report.xml

      - name: Report lint
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: 'report.xml'
          check_name: 'Lint Report'
          annotate_only: ${{ (github.event.pull_request.head.repo.full_name != github.repository) }}

  lua-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup lua
        uses: Liquipedia/gh-actions-lua@316cadd2e8345ee977caa64ac0d192e15d932f73
        with:
          luaVersion: '5.1'

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Setup dependencies
        run: |
          luarocks install --lua-version=5.1 busted

      - name: Run test
        run: |
          busted -C lua -v --run=ci --output=junit > busted.xml

      - name: Report test
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: 'busted.xml'
          check_name: 'Lua Test Report'
          annotate_only: ${{ (github.event.pull_request.head.repo.full_name != github.repository) }}
