name: Protect newly set up wiki

on:
  workflow_dispatch:
    inputs:
      wiki:
        description: 'Wiki to set up'
        required: true

jobs:
  protect:
    if: github.ref_name == github.event.repository.default_branch
    name: Protect modules on newly set up wiki
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Python Dependency
        run: pip install requests

      - name: Lua Protect
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          WIKI_TO_PROTECT: ${{ github.event.inputs.wiki }}
          PYTHONUNBUFFERED: 1
        run: python3 ./scripts/protect.py
