name: Scheduled Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1,4'

jobs:
  deploy:
    name: LP Wikis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install Python Dependency
        run: pip install requests

      - name: Resource Deploy
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          DEPLOY_TRIGGER: ${{ github.event_name }}
          PYTHONUNBUFFERED: 1
        run: python3 ./scripts/deploy_res.py

      - name: Lua Deploy
        env:
          WIKI_USER: ${{ secrets.LP_BOTUSER }}
          WIKI_PASSWORD: ${{ secrets.LP_BOTPASSWORD }}
          WIKI_UA_EMAIL: ${{ secrets.LP_UA_EMAIL }}
          WIKI_BASE_URL: ${{ secrets.LP_BASE_URL }}
          DEPLOY_TRIGGER: ${{ github.event_name }}
          PYTHONUNBUFFERED: 1
        run: python3 ./scripts/deploy.py
